
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: "k10-gcs-{{ .Values.bucketname }}-secret"
  namespace: kasten-io     
data:
  project-id: {{ .Values.projectid | b64enc }}
  service-account.json: {{ .Values.gcekey }}