
apiVersion: v1
kind: Secret
type: Opaque             
metadata:
  name: "k10-gcs-{{ .Values.bucketname }}-secret"
  namespace: kasten-io     
stringData:
  project-id: "{{ .Values.projectid }}"
  service-account.json: "{{ .Values.gcekey }}" 