apiVersion:   storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
      storageclass.kubernetes.io/is-default-class: "{{ .Values.DefaultClass }}"
  name: csi-sc-{{ .Release.Name }}
parameters:
  tagSpecification_1:   {{ .Values.Owner | quote }}
  tagSpecification_2:   {{ .Values.Activity | quote }}
provisioner:   ebs.csi.aws.com
reclaimPolicy:   Delete
volumeBindingMode:   WaitForFirstConsumer