apiVersion:   snapshot.storage.k8s.io/v1
kind:   VolumeSnapshotClass
metadata:
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
  name: csi-ebs-vsc-{{ .Release.Name }}
driver:   ebs.csi.aws.com
deletionPolicy:   Delete