apiVersion: v1
kind: Secret
type: secrets.kanister.io/azure             
metadata:
  name: "k10-azblob-{{ .Values.K10Location.bucketname }}-secret"
  namespace: kasten-io     
stringData:
  azure_storage_account_id: "{{ .Values.K10Location.bucketname }}"
  azure_storage_environment: "{{ .Values.K10Location.azure_storage_env }}"
  azure_storage_key: "{{ .Values.K10Location.azure_storage_key }}"