apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: "{{ .Values.K10Location.clustername }}-{{ .Values.K10Location.bucketname }}"
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AzStorageAccount
      secret:
        apiVersion: v1
        kind: Secret
        name: "k10-azblob-{{ .Values.K10Location.bucketname }}-secret"
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      name: "k10"
      objectStoreType: AZ
      pathType: "Directory"

