
apiVersion: v1
kind: Secret
type: secrets.kanister.io/aws             
metadata:
  name: "k10-awss3-{{ .Values.bucketname }}-secret"
  namespace: kasten-io     
stringData:
  aws_access_key_id: "{{ .Values.aws_access_key }}"
  aws_secret_access_key: "{{ .Values.aws_secret_access_key }}"